baseURL: "https://josedelapuente.com/"
enableRobotsTXT: true
languageCode: en-us
title: José de la Puente | Python and Platform engineering
theme: "PaperMod"
params:
  defaultTheme: dark
  description: "Software engineer specialized in Python internals, compilation and linking, distributed systems, and user experience design. Creator of the Horus observability system."
  disableThemeToggle: true
  hideFooter: true
  homeInfoParams:
    Content: |
      I'm a software engineer at [Thought Machine](https://thoughtmachine.net), where I've been working on backend and platform engineering. I care about working on high-leverage problems with business impact.

      I also built [Horus](https://tryhorus.com), a full-stack observability system for distributed microservices.

      My current interests include:

      - How will technology reshape around voice as an interface? [Some hypotheses here](https://josedelapuente.com/posts/ais-iphone-moment/)
      - Python and Linux internals
      - Mathematics and literature
  env: production
  socialIcons:
    - name: "twitter"
      url: "https://twitter.com/jadelapuente"
    - name: "github"
      url: "https://github.com/jadelapuente"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/jadelapuente/"
    - name: "email"
      url: "mailto:14jdelap@gmail.com"
  label:
    text: "José de la Puente"
  isProduction: true
  images: ["/images/The_Fighting_Temeraire,_JMW_Turner,_National_Gallery.jpg"]
  imagesLazyLoading: true
pygmentsOptions: "linenos=table"
